config/routes.rb
Treebook::Application.routes.draw do
  get "profiles/show"
  

  as :user do
  get '/register', to: 'devise/registrations#new', as: :register 
  get '/login', to: 'devise/sessions#new', as: :login 
  get '/logout', to: 'devise/sessions#destroy', as: :logout 
  end  

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/login" => 'devise/sessions#destroy', as: :destroy_user_session
  end  

  resources :user_friendships do
    member do
      put :accept
    end
  end    
  
  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed

  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/status.rb
class Status < ActiveRecord::Base
	
	attr_accessible :content, :user_id
	belongs_to :user

	validates :content, presence: true, length: {minimum: 2, maximum:50}

	validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, 
  :first_name, :last_name, :profile_name, :email

  validates :first_name, presence: true

  validates :last_name, presence: true

  validates :profile_name, presence: true, uniqueness: true, format: {
                            with: /\A[a-zA-Z]+\z/,  message: "Must be formatted correctly."
                          }

  has_many :statuses
  has_many :user_friendships
  has_many :friends, through: :user_friendships, 
                    conditions: {user_friendships: {state: 'accepted'} }

  has_many :pending_user_friendships, class_name: 'UserFriendship', 
                                      foreign_key: :user_id,
                                      conditions: {state: 'pending'}
  has_many :pending_friends, through: :pending_user_friendships, source: :friend  



  def full_name
    first_name + " " + last_name
  end 
  
  def to_param

    profile_name
  end

  def gravatar_url

    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)

    "http://gravatar.com/avatar/#{hash}"
  end
  

end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
	
	belongs_to :user
	belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'


	attr_accessible :user, :friend, :user_id, :friend_id, :state 

	after_destroy :delete_mutual_friendship!

	state_machine :state, initial: :pending do	

		after_transition on: :accept, do: [:send_acceptance_email, :accept_mutual_friendship!]

		state :requested	

		event :accept do
			transition any => :accepted
		end	
	end

	def self.request(user1, user2)
		transaction do
			friendship1 = create!(user: user1, friend: user2, state: 'pending')
			friendship2 = create!(user: user2, friend: user1, state: 'requested')

			friendship1.send_request_email
			friendship1
		end
	end	

	def send_request_email
		UserNotifier.friend_requested(id).deliver
	end	

	def send_acceptance_email
		UserNotifier.friend_request_accepted(id).deliver
	end

	def mutual_friendship
		self.class.where({user_id: friend_id, friend_id: user_id}).first
	end	

	def accept_mutual_friendship!
		# Grab the mutual friendship and update without using callback
		mutual_friendship.update_attribute(:state, 'accepted')
	end	

	def delete_mutual_friendship!
		mutual_friendship.delete
	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :profile_name, :email, :password, :password_confirmation, :remember_me) }

  end

  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user =User.find_by_profile_name(params[:id])
  	if @user 
  		@statuses = @user.statuses.all
  		render action: :show
  	else
  		render file: 'public/404', status: 404, formats: [:html]
  	end	
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name,:content, :user_id, :first_name)
    end
end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
before_filter :authenticate_user!

	def index
		@user_friendship = current_user.user_friendships.all
	end

	def accept
		@user_friendship = current_user.user_friendships.find(params[:id])
		if @user_friendship.accept!
			flash[:success] = "You are now friends with #{@user_friendship.friend.first_name}"
		else
			flash[:error] = "That friendship could not be accepted"
		end
				
		redirect_to user_friendships_path

	end

	def new
		if params[:friend_id]
			@friend = User.where(profile_name: params[:friend_id]).first
			raise ActiveRecord::RecordNotFound if @friend.nil?
			@user_friendship = current_user.user_friendships.new(friend: @friend)

		else	
			flash[:error] = "Friend required"
		end
	rescue ActiveRecord::RecordNotFound 
		render file: 'public/404', status: :not_found

	end

	def create
		if params[:user_friendship] && params[:user_friendship].has_key?(:friend_id)
		@friend = User.where(profile_name: params[:user_friendship][:friend_id]).first
		@user_friendship = UserFriendship.request(current_user, @friend)
		if @user_friendship.new_record?
			flash[:error] = "There was a problem creating that friend request"
		else
			flash[:success] = "Friend request send"
		end		

		redirect_to profile_path(@friend)

		else
			flash[:error] = "Friend required"
			redirect_to root_path
		end	
	end

	def edit
		@user_friendship = current_user.user_friendships.find(params[:id])
		@friend = @user_friendship.friend
	end

	def destroy
	@user_friendship = current_user.user_friendships.find(params[:id])
	if @user_friendship.destroy
		flash[:success] = "Frienship destroy"
	end	
	redirect_to user_friendships_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class (type)
		case type
		when :alert
			"alert-danger"
		when :notice
			"alert-success"
		else
			""
		end	
 	end	
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse" role="navigation">
		<div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="navbar-brand"> 
        <%= link_to "Treebook", feed_path%>
      </ul>
    </div>

     <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "All statuses", feed_path %></li>
      </ul> 

      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>

          <li><%= link_to "Friends", user_friendships_path %></li>

          <li><%= link_to current_user.email, edit_user_registration_path %></li>
          <li><%= link_to "Log Out", logout_path %></li>

        <% else %>
      
          <li><%= link_to "Register", register_path %></li> 
          <li><%= link_to "Log in", login_path %></li> 

        <% end %>  

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


      <!-- Old code

      <ul class="nav"> 
			<li><a href="#" class="brand">Treebook</a></li>
		  <li><%= link_to "All statuses", feed_path %></li>
      </ul>
      <ul class="navbar-text navbar-right">

        <% if user_signed_in? %>

          <li><%= link_to current_user.email, edit_user_registration_path %></li>
          <li><%= link_to "Log Out", logout_path %></li>

        <% else %>
      
          <li><%= link_to "Register", register_path %></li> 
          <li><%= link_to "Log in", login_path %></li> 

        <% end %>  

      </ul>

		</div>
</nav> 	-->

<div class="container">
  <% flash.each do |type, message| %>
    <div class="alert <%= flash_class type %>">
      <button class="close" data-dismiss="alert"></button>
        <%= message %>
    </div>
  <% end %>


<%= yield %>


</body>
</html>

app/views/profiles/show.html.erb
<div class= "page header">
	<h1> <%= @user.full_name %> </h1>	
	<%= link_to "Add friend", new_user_friendship_path(friend_id: @user), class:'btn'%>
</div>

<% if @statuses %>
	<% @statuses.each do |status| %>
		<div class="well">
			<%= status.content %>
			<hr />
			<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
		</div>
	<% end %>
<% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: 'form-horizontal'}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <%= f.input :content %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
<h1>All statuses</h1>
</div>

<%= link_to "Post a New Status", new_status_path, class:"btn btn-success" %>

<% @statuses.each do |status| %>
<div class="status">
	<div class= "row">
		<div class="col-md-1">
			<%= link_to image_tag(status.user.gravatar_url), profile_path(status.user) %> 
		</div>	 
		<div class="col-md-4">
  			<strong><%= status.user.full_name %></strong>
  			<p><%= status.content %></p>
  			<div class="meta">
  				<%= link_to time_ago_in_words(status.created_at) + " ago", status %>
  				<span class="admin">
    				| <%= link_to "Edit", edit_status_path(status) %> |
    				<%= link_to "Delete", status, method: :delete,data: { confirm: 'Are you sure?' } %>
  				</span>
  			</div>
		</div>
	</div>
</div>

<% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.user.email %> <br />

  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/user_friendships/edit.html.erb
<div class="page-header">
  <h1>Viewing Friendship</h1>
</div>

<div>

  <% if @user_friendship.requested? %>
  <h3>Do you really want to be friends with <%= @friend.first_name %>?</h3>
  <% end %>

    <div class="form-actions">
      <% if @user_friendship.requested? %>
        <%= form_for @user_friendship, url: accept_user_friendship_path(@user_friendship), method: :put do |form| %>
          <%= submit_tag "Accept Friendship", class: 'btn btn-primary' %>
        <% end %>
      <% end %>

      <% if @user_friendship.accepted? %>
        <%= form_for @user_friendship, url: user_friendship_path(@user_friendship), method: :delete do |form| %>
          <%= submit_tag "Delete Friendship", class: 'btn btn-danger' %>
        <% end %>
      <% end %>
    </div>
</div>

app/views/user_friendships/index.html.erb
<div class="page-header">
  <h1>Friends</h1>
</div>

<% @user_friendship.each do |friendship| %>
  <% friend = friendship.friend %>
  <div id="<%= dom_id(friendship) %>" class="friend row">
    <div class="span1">
      <%= link_to image_tag(friend.gravatar_url), profile_path(friend) %>
    </div>
    <div class="span7">
      <strong><%= friend.full_name %></strong><br />
        <% if friendship.pending? %>
          <em>Friendship is pending.</em> <%= link_to "Delete request", edit_user_friendship_path(friendship) %>.
        <% end %>
        <% if friendship.requested? %>
          <em>Friendship requested.</em> <%= link_to "Accept Friendship", edit_user_friendship_path(friendship) %>.
        <% end %>
        <% if friendship.accepted? %>
          <em>Friendship started <%= friendship.updated_at %>.</em> <%= link_to "Update friendship", edit_user_friendship_path(friendship) %>.
        <% end %>
    </div>
  </div>
<% end %>

app/views/user_friendships/new.html.erb
<% if @friend %>
	<h1><%= @friend.email %><h1>

	<p>Do you really want to friend <%= @friend.email %>?</p>

	<%= form_for @user_friendship, method: :post do |form| %>
		<div class="for form-actions">
			<%= form.hidden_field :friend_id, value: @friend.profile_name %>
			<%= submit_tag "Yes, Add friend", class: 'btn btn-primary' %>
			<%= link_to "Cancel", profile_path(@friend), class:'btn' %>
		</div>

	<% end %>
<% end %>

app/views/user_notifier/friend_request_accepted.html.erb
Hi <%= @friend.first_name %>

<%= @user.first_name %> has accepted your friend request. Isn't that great?

Love,
Mike The Frog

app/views/user_notifier/friend_requested.html.erb
Hi <%= @friend.first_name %>

<%= @user.first_name %> wanrs to be friends on Treebook. Isn't that great?

Love,
Mike The Frog